#!/bin/bash
echo "🚀 Deploying to Vercel..."
echo ""
echo "Step 1: Make sure you're logged in to Vercel"
echo "  Run: vercel login"
echo ""
echo "Step 2: Deploy"
echo "  Run: vercel"
echo ""
echo "Or deploy to production:"
echo "  Run: vercel --prod"
echo ""
echo "📝 Don't forget to add environment variables in Vercel dashboard:"
echo "  - VITE_SUPABASE_URL"
echo "  - VITE_SUPABASE_ANON_KEY"
